# Generated by Django 4.0.3 on 2022-04-23 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoAPagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaSolicitud', models.DateTimeField(auto_now_add=True)),
                ('fechaAprobacion', models.DateTimeField(null=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Analista', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
