# Generated by Django 4.0.4 on 2022-05-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloFinanciero', '0002_alter_solicitudcredito_analista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteEstrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('carrera', models.CharField(default='', max_length=50)),
                ('ciudad', models.CharField(default='', max_length=50)),
                ('universidad', models.CharField(default='', max_length=50)),
                ('genero', models.CharField(default='', max_length=50)),
                ('edad', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloFinanciero.estudianteestrella'),
        ),
    ]
