# Generated by Django 4.0.2 on 2022-03-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=100)),
                ('tipoDeTrabajo', models.CharField(max_length=50)),
                ('industria', models.CharField(max_length=50)),
                ('tipoExperiencia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
