# Generated by Django 4.0.3 on 2022-05-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManejadorBancaEmpleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('representanteLegal', models.CharField(max_length=70)),
                ('sector', models.CharField(max_length=50)),
                ('cantidadEmpleados', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudesEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
    ]
